server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:h2:mem:PedidoDB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  file:
    name: /home/rag/ws4-pedidos-productos-usuarios/Logging/log-central.log
