server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:h2:mem:ProductoDB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  file:
    name: /home/rag/ws4-pedidos-productos-usuarios/Logging/log-central.log
---
spring:
  profiles: docker
  datasource:
    url: jdbc:h2:mem:ProductoDB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 9002
  
logging:
  file:
    name: /log-central.log
