server:
  port: 9001
  
spring:
  datasource:
    url: jdbc:h2:mem:UsuarioDB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  file:
    name: /home/rag/ws4-pedidos-productos-usuarios/Logging/log-central.log
