server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    user:
      name: user
      password: password
      role: USER
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
zuul:
  routes:
    pedidos:
      path: /creaPedido
      service-id: pedidos
      strip-prefix: false
---
spring:
  profiles: docker
  security:
    user:
      name: user
      password: password
      role: USER

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
zuul:
  routes:
    pedidos:
      path: /creaPedido
      service-id: pedidos
      strip-prefix: false
  host:
    time-to-live: -1
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500      
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

